version: '3'
services:
 postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: store_app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: